server {
    listen 80;
    root /usr/share/nginx/html;
    index clientes.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = / {
        return 302 /clientes.html;
    }

    location = /admin {
        return 302 /clientes.html;
    }

    location = /clientes {
        return 302 /clientes.html;
    }

    location = /agencia {
        return 302 /agencia.html;
    }
}
